# TCL File Generated by Component Editor 18.1
# Sat Nov 06 18:13:34 CET 2021
# DO NOT MODIFY


# 
# DMA_LCD "DMA_LCD" v1.0
#  2021.11.06.18:13:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DMA_LCD
# 
set_module_property DESCRIPTION ""
set_module_property NAME DMA_LCD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DMA_LCD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DMA_LCD_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DMA_LCD_ctrl.vhd VHDL PATH DMA_LCD_ctrl.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon
# 
add_interface avalon avalon end
set_interface_property avalon addressUnits WORDS
set_interface_property avalon associatedClock clk
set_interface_property avalon associatedReset reset_sink
set_interface_property avalon bitsPerSymbol 8
set_interface_property avalon burstOnBurstBoundariesOnly false
set_interface_property avalon burstcountUnits WORDS
set_interface_property avalon explicitAddressSpan 0
set_interface_property avalon holdTime 0
set_interface_property avalon linewrapBursts false
set_interface_property avalon maximumPendingReadTransactions 0
set_interface_property avalon maximumPendingWriteTransactions 0
set_interface_property avalon readLatency 0
set_interface_property avalon readWaitTime 1
set_interface_property avalon setupTime 0
set_interface_property avalon timingUnits Cycles
set_interface_property avalon writeWaitTime 0
set_interface_property avalon ENABLED true
set_interface_property avalon EXPORT_OF ""
set_interface_property avalon PORT_NAME_MAP ""
set_interface_property avalon CMSIS_SVD_VARIABLES ""
set_interface_property avalon SVD_ADDRESS_GROUP ""

add_interface_port avalon avalon_address address Input 3
add_interface_port avalon avalon_waitrequest waitrequest Output 1
add_interface_port avalon avalon_cs chipselect Input 1
add_interface_port avalon avalon_rd read Input 1
add_interface_port avalon avalon_read_data readdata Output 32
add_interface_port avalon avalon_wr write Input 1
add_interface_port avalon avalon_write_data writedata Input 32
set_interface_assignment avalon embeddedsw.configuration.isFlash 0
set_interface_assignment avalon embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clk
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_readdata readdata Input 16
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clk
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


# 
# connection point conduit_CS_n
# 
add_interface conduit_CS_n conduit end
set_interface_property conduit_CS_n associatedClock clk
set_interface_property conduit_CS_n associatedReset reset_sink
set_interface_property conduit_CS_n ENABLED true
set_interface_property conduit_CS_n EXPORT_OF ""
set_interface_property conduit_CS_n PORT_NAME_MAP ""
set_interface_property conduit_CS_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_CS_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_CS_n LCD_CS_n export Output 1


# 
# connection point conduit_D_C_n
# 
add_interface conduit_D_C_n conduit end
set_interface_property conduit_D_C_n associatedClock clk
set_interface_property conduit_D_C_n associatedReset reset_sink
set_interface_property conduit_D_C_n ENABLED true
set_interface_property conduit_D_C_n EXPORT_OF ""
set_interface_property conduit_D_C_n PORT_NAME_MAP ""
set_interface_property conduit_D_C_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_D_C_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_D_C_n LCD_D_C_n export Output 1


# 
# connection point conduit_IM0
# 
add_interface conduit_IM0 conduit end
set_interface_property conduit_IM0 associatedClock clk
set_interface_property conduit_IM0 associatedReset reset_sink
set_interface_property conduit_IM0 ENABLED true
set_interface_property conduit_IM0 EXPORT_OF ""
set_interface_property conduit_IM0 PORT_NAME_MAP ""
set_interface_property conduit_IM0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_IM0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_IM0 LCD_IM0 export Output 1


# 
# connection point conduit_RD
# 
add_interface conduit_RD conduit end
set_interface_property conduit_RD associatedClock clk
set_interface_property conduit_RD associatedReset reset_sink
set_interface_property conduit_RD ENABLED true
set_interface_property conduit_RD EXPORT_OF ""
set_interface_property conduit_RD PORT_NAME_MAP ""
set_interface_property conduit_RD CMSIS_SVD_VARIABLES ""
set_interface_property conduit_RD SVD_ADDRESS_GROUP ""

add_interface_port conduit_RD LCD_RD export Output 1


# 
# connection point conduit_WR_n
# 
add_interface conduit_WR_n conduit end
set_interface_property conduit_WR_n associatedClock clk
set_interface_property conduit_WR_n associatedReset reset_sink
set_interface_property conduit_WR_n ENABLED true
set_interface_property conduit_WR_n EXPORT_OF ""
set_interface_property conduit_WR_n PORT_NAME_MAP ""
set_interface_property conduit_WR_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_WR_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_WR_n LCD_WR_n export Output 1


# 
# connection point conduit_RES
# 
add_interface conduit_RES conduit end
set_interface_property conduit_RES associatedClock clk
set_interface_property conduit_RES associatedReset reset_sink
set_interface_property conduit_RES ENABLED true
set_interface_property conduit_RES EXPORT_OF ""
set_interface_property conduit_RES PORT_NAME_MAP ""
set_interface_property conduit_RES CMSIS_SVD_VARIABLES ""
set_interface_property conduit_RES SVD_ADDRESS_GROUP ""

add_interface_port conduit_RES LCD_RES export Output 1


# 
# connection point conduit_data
# 
add_interface conduit_data conduit end
set_interface_property conduit_data associatedClock clk
set_interface_property conduit_data associatedReset reset_sink
set_interface_property conduit_data ENABLED true
set_interface_property conduit_data EXPORT_OF ""
set_interface_property conduit_data PORT_NAME_MAP ""
set_interface_property conduit_data CMSIS_SVD_VARIABLES ""
set_interface_property conduit_data SVD_ADDRESS_GROUP ""

add_interface_port conduit_data LCD_data export Output 16


# 
# connection point conduit_end_of_transaction_irq
# 
add_interface conduit_end_of_transaction_irq conduit end
set_interface_property conduit_end_of_transaction_irq associatedClock clk
set_interface_property conduit_end_of_transaction_irq associatedReset reset_sink
set_interface_property conduit_end_of_transaction_irq ENABLED true
set_interface_property conduit_end_of_transaction_irq EXPORT_OF ""
set_interface_property conduit_end_of_transaction_irq PORT_NAME_MAP ""
set_interface_property conduit_end_of_transaction_irq CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_of_transaction_irq SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_of_transaction_irq end_of_transaction_irq export Output 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk signalsClk clk Input 1

